# At the time of writing this there was a bug in all other flink
# images which prevented the cluster to start correctly. The bug was
# fixed in the docker-flink repo, but only the hadoop28 alpine image
# was rebuilt.
FROM flink:1.6.1-hadoop28-scala_2.11-alpine


# Environment is inherited from the parent image
# FLINK_VERSION=1.6.1
# FLINK_HOME=/opt/flink
# WORKDIR $FLINK_HOME

RUN cp $FLINK_HOME/opt/flink-s3-fs-hadoop-$FLINK_VERSION.jar \
       $FLINK_HOME/opt/flink-cep_2.11-$FLINK_VERSION.jar \
       $FLINK_HOME/opt/flink-cep-scala_2.11-$FLINK_VERSION.jar \
       $FLINK_HOME/opt/flink-queryable-state-runtime_2.11-$FLINK_VERSION.jar \
       $FLINK_HOME/opt/flink-metrics-prometheus-$FLINK_VERSION.jar \
       $FLINK_HOME/opt/flink-table_2.11-$FLINK_VERSION.jar \
       $FLINK_HOME/lib 

COPY 1.6/lib/* lib/
